# Use the official Node.js image as the base image
FROM node:latest AS build

WORKDIR /app
RUN npm install -g @angular/cli@13
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
EXPOSE 80
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "80"]
