# Use a lightweight image for serving the Angular app
FROM nginx:latest

# Copy the built app from the build stage to the NGINX public directory
COPY --from=angular /app/dist /usr/share/nginx/html

# Expose port 80 (default port for NGINX)
EXPOSE 80

# Start NGINX when the container starts
CMD ["nginx", "-g", "daemon off;"]
